name: Deployment for Document PDF services

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.SERVICES_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SERVICES_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SERVICES_AZURE_SUBSCRIPTION_ID }}

      - name: Login to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.SERVICES_REGISTRY_URL }}
          username: ${{ secrets.SERVICES_REGISTRY_USERNAME }}
          password: ${{ secrets.SERVICES_REGISTRY_PASSWORD }}

      - name: Build and push container image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.SERVICES_REGISTRY_URL }}/services-generator:${{ github.sha }}

      - name: Deploy to Azure Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          containerAppName: ca-generator
          resourceGroup: tabs
          imageToDeploy: ${{ secrets.SERVICES_REGISTRY_URL }}/services-generator:${{ github.sha }}
          

